-- =============================================================
-- Family Tree App — PostgreSQL Schema v1.0
-- =============================================================
-- No Postgres extensions required.
-- All UUIDs are generated by the application (Python uuid.uuid4(),
-- JS crypto.randomUUID(), Dart Uuid().v4()) and stored as VARCHAR(36).
--
-- Minimum required privilege: CREATE TABLE on the target database.
-- =============================================================

CREATE TABLE IF NOT EXISTS family_trees (
    -- Application-generated UUID (no gen_random_uuid() needed)
    id              VARCHAR(36)   NOT NULL,

    -- Which logical tree this row belongs to
    tree_name       VARCHAR(255)  NOT NULL,

    -- Row type discriminator:
    --   'tree_meta' — one row per tree (top-level metadata)
    --   'node'      — one row per person node
    --   'edge'      — one row per relationship edge
    --   'resource'  — one row per photo/resource
    record_type     VARCHAR(50)   NOT NULL,

    -- The original UUID of the object (node id, edge id, resource id, or tree_id)
    record_id       VARCHAR(255)  NOT NULL,

    -- Schema version, e.g. '1.0'
    tree_version    VARCHAR(20)   NOT NULL DEFAULT '1.0',

    -- Full JSON payload for this record (see shared schema in Plan.md)
    payload         JSONB         NOT NULL,

    -- Base64-encoded JPEG image data, compressed to <= 2 MB.
    -- Only populated for record_type = 'resource'. NULL for all other types.
    image_data      TEXT          DEFAULT NULL,

    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    -- Primary key: a given record within a given tree can only appear once
    CONSTRAINT pk_family_trees PRIMARY KEY (tree_name, record_type, record_id),

    -- id must also be globally unique across all trees
    CONSTRAINT uq_family_trees_id UNIQUE (id)
);

-- -----------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------

-- Efficiently list all trees (SELECT DISTINCT tree_name)
CREATE INDEX IF NOT EXISTS idx_ft_tree_name
    ON family_trees (tree_name);

-- Efficiently fetch all nodes / all edges / all resources for a tree
CREATE INDEX IF NOT EXISTS idx_ft_record_type
    ON family_trees (tree_name, record_type);

-- Full-text / containment queries on the JSON payload
CREATE INDEX IF NOT EXISTS idx_ft_payload_gin
    ON family_trees USING GIN (payload);

-- -----------------------------------------------------------------
-- Auto-update updated_at trigger
-- (uses only built-in PL/pgSQL — no extensions needed)
-- -----------------------------------------------------------------

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_family_trees_updated_at ON family_trees;

CREATE TRIGGER trg_family_trees_updated_at
    BEFORE UPDATE ON family_trees
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =============================================================
-- Example: Upsert a node row (run from application code)
-- =============================================================
--
-- INSERT INTO family_trees
--     (id, tree_name, record_type, record_id, tree_version, payload, image_data)
-- VALUES
--     (%(id)s, %(tree_name)s, %(record_type)s, %(record_id)s,
--      %(tree_version)s, %(payload)s::jsonb, %(image_data)s)
-- ON CONFLICT (tree_name, record_type, record_id)
-- DO UPDATE SET
--     payload      = EXCLUDED.payload,
--     image_data   = EXCLUDED.image_data,
--     tree_version = EXCLUDED.tree_version,
--     updated_at   = NOW();
--
-- =============================================================
-- Example: List all tree names
-- =============================================================
--
-- SELECT DISTINCT tree_name FROM family_trees ORDER BY tree_name;
--
-- =============================================================
-- Example: Delete a tree (confirm tree name in app before running)
-- =============================================================
--
-- DELETE FROM family_trees WHERE tree_name = %(tree_name)s;
--
-- =============================================================

